# description
name: "magicznyleszek presents"
description: "A fistful of drawings and projects by Leszek Pietrzak, a Polish-born illustrator, designer and front-end developer."
keywords: "frontend developer, icon designer, illustrator, unicorn, portfolio"
author: "Leszek Pietrzak"
email: "leszek@magicznyleszek.xyz"
language: "en-US"

# address settings
rootSiteUrl: "https://magicznyleszek.xyz"
baseurl: "https://portfolio.magicznyleszek.xyz"

# urls
googleFontsCode: family=Source+Sans+Pro:400,700,400italic,700italic&subset=latin,latin-ext

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: false
timezone: Europe/Warsaw
# 0 to 65535
port: 2038

exclude:
  - bin
  - node_modules
  - LICENSE
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - VERSION.md
